---
- name: "Gather Information"
# Use the -e option to specify the hostnames # -e "host=all" or 
# -e "host=building_1", etc...
  hosts: "{{ host }}"
  gather_facts: no

  vars_prompt:
    - name: "host"
      prompt: "Enter hostname, building, room, or device type"
      private: no
    - name: "ansible_user"
      prompt: "Enter username"
      private: no
    - name: "ansible_password"
      prompt: "Enter password"
      private: yes

  tasks: 
    - name: Create backup dir
      file:
        path: "./outputs/backups/{{ inventory_hostname }}"
        state: directory
        recurse: yes
    - name: Backup switch (JunOS)
      junipernetworks.junos.junos_config:
        backup: yes
        backup_options:
          dir_path: "./outputs/backups/{{ inventory_hostname }}"