- name: "Configure interface"
# Use the -e option to specify the hostnames # -e "host=all" or 
# -e "host=building_1", etc...
  hosts: "{{ host }}"
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  vars_files:
    - ./secrets/vault-vars.yml    
  tasks:
  - name: Configure access interface with description and VLAN
    juniper_junos_config:
      lines:
        - "delete interfaces {{ item.name }}"
        - "set interfaces {{ item.name }} description '{{ item.description }}'"
        - "set interfaces {{ item.name }} unit 0 family ethernet-switching interface-mode access"
        - "set interfaces {{ item.name }} unit 0 family ethernet-switching vlan members {{ item.vlan }}"
      timeout: 300
      ignore_warning: true
      provider: "{{ user_credentials }}"
# Create an item for each interface you wish to change. Each item should have 
# the name, description, and vlan
    with_items:
      - name: ge-0/0/0
        description: Test description
        vlan: 200
    register: response
  - name: Print response
    debug:
      var: response