---
- name: Grab facts from devices
  hosts: "{{ host }}"
  gather_facts: no

  vars_prompt:
    - name: "host"
      prompt: "Enter hostname, building, room, or device type"
      private: no
    - name: "ansible_user"
      prompt: "Enter username"
      private: no
    - name: "ansible_password"
      prompt: "Enter password"
      private: yes

  tasks:
    - name: Grab facts
      junipernetworks.junos.junos_facts:

      register: result
    - name: Print to stdout
      debug:
        var: result